x-common-env: &common-env
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"

services:
  app:
    build: .
    container_name: asssment-app
    env_file:
      - .env
    environment:
      <<: *common-env
      MONGODB_URI: mongodb://mongo:27017/asssment
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: asssment-worker
    command: npm run worker
    env_file:
      - .env
    environment:
      <<: *common-env
      MONGODB_URI: mongodb://mongo:27017/asssment
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongo:
    image: mongo:7.0.34-jammy
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
