name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile

          push: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/asssment:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/asssment:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

          platforms: linux/amd64
